matrix:
  include:

    # R
    - language: R
      cache: packages
      before_install:
      - cd R/

    # python
    - language: python
      #python: 2.7
      #install:
        #- pip install -r requirements.txt
      before_script:
        - cd python/
      script:
        - pytest
