matrix:

  include:

    # R linux
    ##########################

    - name: "R-release Linux"
      language: r
      os: linux
      r: release
      cache: packages
      before_install:
        - cd R/
      after_success:
        - Rscript -e "covr::codecov()"

    - name: "R-devel Linux"
      language: r
      os: linux
      r: devel
      cache: packages
      before_install:
        - cd R/

    - name: "R-oldrel Linux"
      language: r
      os: linux
      r: oldrel
      cache: packages
      before_install:
        - cd R/

    # R osx
    ##########################

    - name: "R-release OSX"
      language: r
      os: osx
      r: release
      cache: packages
      before_install:
        - sudo tlmgr install framed titling
        - cd R/

    - name: "R-oldrel OSX"
      language: r
      os: osx
      r: oldrel
      cache: packages
      before_install:
        - sudo tlmgr install framed titling
        - cd R/

    # Python
    ##########################

    - name: "Python Linux"
      language: python
      python: 3.7
      os: linux
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=motifcluster tests/
      after_success:
        - coveralls

    - name: "Python OSX"
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - pip3 install -U pip
        - pip3 install -U pytest
        - cd python/
      install:
        - pip3 install -r requirements.txt
      script:
        - python3 -m pytest tests/
