matrix:
  include:

    # R release
    - language: r
      r: release
      cache: packages
      before_install:
        - cd R/
      after_success:
        - Rscript -e "covr::codecov()"


    # R devel
    - language: r
      r: devel
      cache: packages
      before_install:
        - cd R/


    # R oldrel
    - language: r
      r: oldrel
      cache: packages
      before_install:
        - cd R/


    # python
    - language: python
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=motifcluster tests/
      after_success:
        - coveralls
