matrix:

  include:

    # R linux
    ##########################

    # R-release linux
    - language: r
      os: linux
      r: release
      cache: packages
      before_install:
        - cd R/
      after_success:
        - Rscript -e "covr::codecov()"

    # R-devel linux
    - language: r
      os: linux
      r: devel
      cache: packages
      before_install:
        - cd R/

    # R-oldrel linux
    - language: r
      os: linux
      r: oldrel
      cache: packages
      before_install:
        - cd R/

    # R osx
    ##########################

    # R-release osx
    - language: r
      os: osx
      r: release
      cache: packages
      before_install:
        - sudo tlmgr install framed titling
        - cd R/


    # R-devel osx
    - language: r
      os: osx
      r: devel
      cache: packages
      before_install:
        - sudo tlmgr install framed titling
        - cd R/

    # R-oldrel osx
    - language: r
      os: osx
      r: oldrel
      cache: packages
      before_install:
        - sudo tlmgr install framed titling
        - cd R/

    # Python
    ##########################

    # Python linux
    - language: python
      os: linux
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=motifcluster tests/
      after_success:
        - coveralls

    # Python osx
    - language: python
      os: osx
      osx_image: xcode10.2
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest tests/
