os:
  - linux
  - osx


matrix:
  include:

    # R
    - language: R
      cache: packages
      before_install:
        - cd R/
      after_success:
        - Rscript -e "covr::codecov()"


    # python
    - language: python
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=motifcluster tests/
      after_success:
        - coveralls
