matrix:
  include:

    # R
    - language: R
      cache: packages
      before_install:
      - cd R/

    # python
    - language: python
      before_install:
        - cd python/
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=motifcluster
      after_success:
        - coveralls
